---
- hosts: localhost
  tasks:
  - name: downloading andconfiguring dispather 
    get_url: 
           url: https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
           dest: /opt/
        
