---
- hosts: localhost
  tasks:
  - name: creating directory
    command: mkdir -p /opt/dispatcher
  - name: downloading andconfiguring dispather 
    get_url: 
           url: https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
           dest: /opt/dispatcher
  - name: Extract archive
    unarchive: 
         src=/opt/dispatcher/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
         dest=/opt/dispatcher
  - name: remove dispather
    command: rm -f /opt/dispatcher/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
